# GoReleaser configuration for DBSmith
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - id: dbsmith
    main: ./cmd/dbsmith
    binary: dbsmith
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
      - -X main.RevisionTime={{.CommitDate}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - config.example.yaml

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: android-lewis
    name: dbsmith
  draft: false
  prerelease: auto
