version: '3'

vars:
  BINARY_NAME: dbsmith
  GO: go
  GOFLAGS: -v
  VERSION: dev
  LDFLAGS: -X main.Version={{.VERSION}}

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  build:
    desc: Build binary for current platform
    cmds:
      - echo "Building {{.BINARY_NAME}}..."
      - '{{.GO}} build {{.GOFLAGS}} -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}} ./cmd/dbsmith'
    platforms: [linux, darwin, windows]

  build:windows:
    desc: Build binary for Windows
    env:
      GOOS: windows
      GOARCH: amd64
    cmds:
      - echo "Building {{.BINARY_NAME}} for Windows..."
      - '{{.GO}} build {{.GOFLAGS}} -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-windows-amd64.exe ./cmd/dbsmith'
    platforms: [windows, linux, darwin]

  build:linux:
    desc: Build binary for Linux (amd64)
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - echo "Building {{.BINARY_NAME}} for Linux..."
      - '{{.GO}} build {{.GOFLAGS}} -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-linux-amd64 ./cmd/dbsmith'
    platforms: [linux, darwin, windows]

  build:darwin:
    desc: Build binary for macOS (Intel & Apple Silicon)
    env:
      GOOS: darwin
    cmds:
      - echo "Building {{.BINARY_NAME}} for macOS (Intel)..."
      - cmd: '{{.GO}} build {{.GOFLAGS}} -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-darwin-amd64 ./cmd/dbsmith'
        env:
          GOARCH: amd64
      - echo "Building {{.BINARY_NAME}} for macOS (ARM64)..."
      - cmd: '{{.GO}} build {{.GOFLAGS}} -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}}-darwin-arm64 ./cmd/dbsmith'
        env:
          GOARCH: arm64
    platforms: [linux, darwin, windows]

  build:all:
    desc: Build binaries for all platforms
    deps: [build:linux, build:darwin, build:windows]

  test:
    desc: Run tests
    cmds:
      - '{{.GO}} test ./...'

  test:verbose:
    desc: Run tests with verbose output and race detection
    cmds:
      - '{{.GO}} test -v ./...'

  test:coverage:
    desc: Run tests with coverage report
    env:
      CGO_ENABLED: 1
    cmds:
      - '{{.GO}} test -v -race -coverprofile=coverage.out ./...'
      - '{{.GO}} tool cover -html=coverage.out -o coverage.html'
      - echo "Coverage report generated coverage.html"

  test:integration:
    desc: Run integration tests with testcontainers (Docker required)
    cmds:
      - echo "Running integration tests with testcontainers..."
      - '{{.GO}} test -v -tags=integration -timeout 5m ./tests/integration/...'

  test:integration:postgres:
    desc: Run PostgreSQL integration tests with testcontainers
    cmds:
      - echo "Running PostgreSQL integration tests..."
      - '{{.GO}} test -v -tags=integration -timeout 5m -run Postgres ./tests/integration/...'

  test:integration:mysql:
    desc: Run MySQL integration tests with testcontainers
    cmds:
      - echo "Running MySQL integration tests..."
      - '{{.GO}} test -v -tags=integration -timeout 5m -run MySQL ./tests/integration/...'

  test:integration:sqlite:
    desc: Run SQLite integration tests (no Docker required)
    cmds:
      - echo "Running SQLite integration tests..."
      - '{{.GO}} test -v -tags=integration -timeout 2m -run SQLite ./tests/integration/...'

  lint:
    desc: Run linter (go vet and optional golangci-lint)
    cmds:
      - echo "Linting code..."
      - '{{.GO}} vet ./...'
      - cmd: golangci-lint run ./...
        ignore_error: true

  fmt:
    desc: Format code with go fmt
    cmds:
      - echo "Formatting code..."
      - '{{.GO}} fmt ./...'

  fmt:check:
    desc: Check if code needs formatting
    cmds:
      - cmd: '{{.GO}} fmt -l ./...'
        ignore_error: false

  deps:
    desc: Download and verify dependencies
    cmds:
      - '{{.GO}} mod download'
      - '{{.GO}} mod verify'

  deps:tidy:
    desc: Tidy up go.mod and go.sum
    cmds:
      - '{{.GO}} mod tidy'

  deps:update:
    desc: Update all dependencies to latest compatible versions
    cmds:
      - '{{.GO}} get -u ./...'
      - '{{.GO}} mod tidy'

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "Cleaning build artifacts..."
      - '{{.GO}} clean'
      - cmd: rm -rf bin/
        ignore_error: true
      - cmd: rm -rf coverage.out coverage.html
        ignore_error: true

  clean:all:
    desc: Clean all generated files including vendor and go.sum
    deps: [clean]
    cmds:
      - cmd: rm -rf vendor/
        ignore_error: true
      - cmd: rm go.sum
        ignore_error: true

  run:
    desc: Build and run the application
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}}
    platforms: [linux, darwin]

  run:windows:
    desc: Build and run the application (Windows)
    deps: [build:windows]
    cmds:
      - ./bin/{{.BINARY_NAME}}-windows-amd64.exe
    platforms: [windows]

  run:debug:
    desc: Run with debug output
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}} debug
    platforms: [linux, darwin]

  run:help:
    desc: Show help
    deps: [build]
    cmds:
      - ./bin/{{.BINARY_NAME}} --help
    platforms: [linux, darwin]

  install:
    desc: Install binary to GOBIN
    deps: [build]
    cmds:
      - '{{.GO}} install ./cmd/dbsmith'

  dev:
    desc: Run full development workflow (fmt, lint, test, build)
    deps: [fmt, lint, test, build]
    cmds:
      - echo "Development build complete!"

  dev:watch:
    desc: Watch for changes and rebuild (requires watchexec)
    cmds:
      - watchexec -e go task dev
    ignore_error: true

  ci:test:
    desc: Run CI test suite (format check, lint, tests, build)
    cmds:
      - task fmt:check
      - task lint
      - task test:coverage
      - task build:all

  ci:build:
    desc: Build release binaries for all platforms
    deps: [build:all]
    cmds:
      - echo "Release binaries built successfully!"
      - cmd: ls -lh bin/
        ignore_error: true
